env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  no-console: off,
  import/extensions: off,
  import/no-duplicates: off,
  no-underscore-dangle: off
  }
